export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const COURSES_ALL_SUCCESS = 'COURSES_ALL_SUCCESS';
export const COURSES_PROGRESSION_SUCCESS = 'COURSES_PROGRESSION_SUCCESS';
export const TASKS_ALL_SUCCESS = 'TASKS_ALL_SUCCESS';
export const RESOURCES_ALL_SUCCESS = 'RESOURCES_ALL_SUCCESS';